name: Terraform Provisioning - Develop branch

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'terraform/**'

  workflow_run:
    workflows: ["CI Pipeline - Build and Test"]
    types:
      - completed

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your AWS region

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/environments/dev/aws/

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/environments/dev/aws/
